const userDetails = {
  name: 'Rahul Bansal',
  firstName: 'Rahul',
  lastName: 'Bansal',
  email: '42.rahulbansal@gmail.com',
  imgUrl: 'https://i.ibb.co/VVbGN5x/Pro-Photo.png',
  address: 'Gurugram, India',
  education: [
    {
      course: 'B.Tech',
      specialisation: 'CSE',
      college: 'Sushant University',
      cgpa: '7.3',
      courseStart: 2020,
      courseEnd: 2024,
      courseType: 'Full Time',
    },
  ],
  technicalSkills: [
    'Frontend',
    'Web Development',
    'Typescript',
    'Web Developer',
    'React.js',
    'Tailwind CSS',
    'HTML and CSS',
    'Javascript',
  ],
  internships: [
    {
      companyName: 'VDoIt',
      profile: 'React Native Intern',
      location: 'Gurugram',
      timeline: {
        startYear: 2024,
        endYear: 2024,
        startMonth: 'Mar',
        endMonth: 'June',
      },
      description:
        'Id eiusmod sit incididunt qui amet ea consequat elit nisi enim. Velit ullamco velit sint ut minim. Labore voluptate proident elit adipisicing nulla dolore voluptate aliqua cupidatat eu exercitation. Ea nulla esse Lorem qui deserunt aute. Dolore nulla commodo occaecat sit do ex id esse nostrud fugiat Lorem.',
      kra: [
        'Aliqua quis ex consectetur pariatur cupidatat officia.',
        'Aliqua quis ex consectetur pariatur cupidatat officia.',
      ],
      keySkills: ['skill1', 'skill2'],
    },
  ],
  experience: [
    {
      companyName: 'VDoit',
      profile: 'Developer',
      location: 'Gurugram',
      timeline: {
        startYear: 2024,
        endYear: 2024,
        startMonth: 'Mar',
        endMonth: 'June',
      },
      description:
        'Id eiusmod sit incididunt qui amet ea consequat elit nisi enim. Velit ullamco velit sint ut minim. Labore voluptate proident elit adipisicing nulla dolore voluptate aliqua cupidatat eu exercitation. Ea nulla esse Lorem qui deserunt aute. Dolore nulla commodo occaecat sit do ex id esse nostrud fugiat Lorem.',
      kra: [
        'Aliqua quis ex consectetur pariatur cupidatat officia.',
        'Aliqua quis ex consectetur pariatur cupidatat officia.',
      ],
      keySkills: ['skill1', 'skill2'],
    },
  ],
};

const listings = [
  {
    ListingID: 1,
    company_name: 'Acme Corporation',
    job_title: 'Software Engineer',
    location: 'San Francisco, CA',
    salary: '$120,000 - $150,000 per year',
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      '2+ years of experience in software development',
      'Proficiency in Java, Python, or C++',
    ],
    logo_url: 'https://example.com/acme_logo.png',
    required_skills: ['Java', 'Python', 'C++', 'Software Development'],
    sector: 'Technology',
  },
  {
    ListingID: 2,
    company_name: 'Tech Innovators',
    job_title: 'Data Scientist',
    location: 'New York, NY',
    salary: '$100,000 - $130,000 per year',
    requirements: [
      "Master's degree in Data Science, Statistics, or related field",
      'Strong analytical and problem-solving skills',
      'Experience with machine learning algorithms and tools',
    ],
    logo_url: 'https://example.com/tech_innovators_logo.png',
    required_skills: ['Data Science', 'Statistics', 'Machine Learning'],
    sector: 'Technology',
  },
  {
    ListingID: 3,
    company_name: 'InnovateTech',
    job_title: 'UX/UI Designer',
    location: 'Berlin, Germany',
    salary: '€60,000 - €80,000 per year',
    requirements: [
      "Bachelor's degree in Design or related field",
      'Proficiency in UX/UI design tools like Sketch, Figma, or Adobe XD',
      'Portfolio showcasing previous design projects',
    ],
    logo_url: 'https://example.com/innovate_tech_logo.png',
    required_skills: ['UX/UI Design', 'Sketch', 'Figma', 'Adobe XD'],
    sector: 'Technology',
  },
  {
    ListingID: 4,
    company_name: 'DigitalSolutions Inc.',
    job_title: 'Full Stack Developer',
    location: 'Seattle, WA',
    salary: '$100,000 - $120,000 per year',
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      '3+ years of experience in full-stack development',
      'Proficiency in JavaScript, HTML, CSS, and Node.js',
    ],
    logo_url: 'https://example.com/digital_solutions_logo.png',
    required_skills: [
      'JavaScript',
      'HTML',
      'CSS',
      'Node.js',
      'Full Stack Development',
    ],
    sector: 'Technology',
  },
  {
    ListingID: 5,
    company_name: 'DataTech Solutions',
    job_title: 'Machine Learning Engineer',
    location: 'Boston, MA',
    salary: '$130,000 - $150,000 per year',
    requirements: [
      "Master's or PhD in Computer Science, Machine Learning, or related field",
      'Experience with machine learning algorithms and frameworks',
      'Strong programming skills in Python or R',
    ],
    logo_url: 'https://example.com/datatech_solutions_logo.png',
    required_skills: [
      'Machine Learning',
      'Python',
      'R',
      'Algorithms',
      'Data Science',
    ],
    sector: 'Technology',
  },
  {
    ListingID: 6,
    company_name: 'CyberTech Innovations',
    job_title: 'Cybersecurity Analyst',
    location: 'Washington, D.C.',
    salary: '$90,000 - $110,000 per year',
    requirements: [
      "Bachelor's degree in Cybersecurity, Information Technology, or related field",
      'Experience in cybersecurity operations and threat analysis',
      'Knowledge of security tools and protocols',
    ],
    logo_url: 'https://example.com/cybertech_innovations_logo.png',
    required_skills: ['Cybersecurity', 'Threat Analysis', 'Security Tools'],
    sector: 'Technology',
  },
  {
    ListingID: 7,
    company_name: 'CloudTech Solutions',
    job_title: 'Cloud Solutions Architect',
    location: 'San Jose, CA',
    salary: '$140,000 - $160,000 per year',
    requirements: [
      "Bachelor's degree in Computer Science, Information Technology, or related field",
      'Experience in designing and implementing cloud solutions',
      'Certifications in cloud platforms like AWS, Azure, or Google Cloud',
    ],
    logo_url: 'https://example.com/cloudtech_solutions_logo.png',
    required_skills: [
      'Cloud Solutions',
      'AWS',
      'Azure',
      'Google Cloud',
      'Architecture',
    ],
    sector: 'Technology',
  },
  {
    ListingID: 8,
    company_name: 'MobileTech Innovations',
    job_title: 'Mobile App Developer',
    location: 'Los Angeles, CA',
    salary: '$80,000 - $100,000 per year',
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      'Experience in mobile app development for iOS or Android',
      'Proficiency in Swift, Objective-C, Java, or Kotlin',
    ],
    logo_url: 'https://example.com/mobiletech_innovations_logo.png',
    required_skills: [
      'Mobile App Development',
      'iOS',
      'Android',
      'Swift',
      'Java',
      'Kotlin',
    ],
    sector: 'Technology',
  },
  {
    ListingID: 9,
    company_name: 'AI Solutions Ltd.',
    job_title: 'AI/ML Research Scientist',
    location: 'Mountain View, CA',
    salary: '$150,000 - $180,000 per year',
    requirements: [
      'PhD in Computer Science, Artificial Intelligence, or related field',
      'Research experience in AI/ML algorithms and models',
      'Strong programming skills in Python, TensorFlow, or PyTorch',
    ],
    logo_url: 'https://example.com/ai_solutions_logo.png',
    required_skills: [
      'Artificial Intelligence',
      'Machine Learning',
      'Python',
      'TensorFlow',
      'PyTorch',
    ],
    sector: 'Technology',
  },
  {
    ListingID: 10,
    company_name: 'BlockchainTech Innovations',
    job_title: 'Blockchain Developer',
    location: 'Austin, TX',
    salary: '$110,000 - $130,000 per year',
    requirements: [
      "Bachelor's degree in Computer Science, Information Technology, or related field",
      'Experience in blockchain development and smart contracts',
      'Proficiency in blockchain platforms like Ethereum, Hyperledger, or Corda',
    ],
    logo_url: 'https://example.com/blockchaintech_innovations_logo.png',
    required_skills: [
      'Blockchain Development',
      'Smart Contracts',
      'Ethereum',
      'Hyperledger',
      'Corda',
    ],
    sector: 'Technology',
  },
];

const companiesAppliedTo = [
  {
    companyName: 'Acme Corporation',
    jobTitle: 'Software Engineer',
    location: 'San Francisco, CA',
    status: 'Applied',
  },
  {
    companyName: 'Tech Innovators',
    jobTitle: 'Data Scientist',
    location: 'New York, NY',
    status: 'Applied',
  },
  {
    companyName: 'InnovateTech',
    jobTitle: 'UX/UI Designer',
    location: 'Berlin, Germany',
    status: 'Applied',
  },
  {
    companyName: 'DigitalSolutions Inc.',
    jobTitle: 'Full Stack Developer',
    location: 'Seattle, WA',
    status: 'Applied',
  },
  {
    companyName: 'DataTech Solutions',
    jobTitle: 'Machine Learning Engineer',
    location: 'Boston, MA',
    status: 'Applied',
  },
  {
    companyName: 'CyberTech Innovations',
    jobTitle: 'Cybersecurity Analyst',
    location: 'Washington, D.C.',
    status: 'Applied',
  },
  {
    companyName: 'CloudTech Solutions',
    jobTitle: 'Cloud Solutions Architect',
    location: 'San Jose, CA',
    status: 'Applied',
  },
  {
    companyName: 'MobileTech Innovations',
    jobTitle: 'Mobile App Developer',
    location: 'Los Angeles, CA',
    status: 'Applied',
  },
  {
    companyName: 'AI Solutions Ltd.',
    jobTitle: 'AI/ML Research Scientist',
    location: 'Mountain View, CA',
    status: 'Applied',
  },
  {
    companyName: 'BlockchainTech Innovations',
    jobTitle: 'Blockchain Developer',
    location: 'Austin, TX',
    status: 'Applied',
  },
];

const loginCredentials = {
  username: 'student',
  password: 'student',
};
export {userDetails, listings, companiesAppliedTo, loginCredentials};
